from datetime import date, timedelta
from django.core.mail import send_mail
from django.db.models import Max, Min


# ─── ACCUMULATION EMAIL (completely separate) ──────────────────────────────────

def send_accumulation_report_email(user, accumulation_rows: list):
    """
    Send a separate accumulation-zone email.
    accumulation_rows: list of dicts with keys:
        symbol, list_name, price, rsi, dist_pct, vol_ratio, score, notes
    """
    if not user.email or not accumulation_rows:
        return

    today_str    = date.today().strftime('%B %d, %Y')
    display_name = user.get_full_name() or user.username
    count        = len(accumulation_rows)

    th = "padding:8px 12px;color:#64748B;font-weight:600;font-size:0.75em;text-transform:uppercase;letter-spacing:.05em;white-space:nowrap;"

    rows_html = ''
    for r in accumulation_rows:
        dist_pct  = r['dist_pct']
        dist_color = '#EF4444' if dist_pct < 0 else '#22C55E'
        dist_arrow = '↓' if dist_pct < 0 else '↑'
        rsi        = r['rsi']
        rsi_color  = '#EF4444' if rsi <= 30 else '#F97316' if rsi <= 35 else '#F59E0B'
        score      = r['score']
        score_color = '#22C55E' if score >= 70 else '#F97316' if score >= 50 else '#F59E0B'

        rows_html += f"""
      <tr style="border-bottom:1px solid #1E293B;">
        <td style="padding:8px 12px;font-weight:700;color:#F97316;">{r['symbol']}</td>
        <td style="padding:8px 12px;color:#475569;font-size:0.8em;">{r['list_name']}</td>
        <td style="padding:8px 12px;text-align:right;font-family:monospace;font-weight:600;color:#F8FAFC;">${r['price']:.2f}</td>
        <td style="padding:8px 12px;text-align:right;font-family:monospace;font-weight:600;color:{rsi_color};">{rsi:.1f}</td>
        <td style="padding:8px 12px;text-align:right;font-family:monospace;color:{dist_color};">{dist_arrow}{abs(dist_pct):.1f}%</td>
        <td style="padding:8px 12px;text-align:right;font-family:monospace;color:#94A3B8;">{r['vol_ratio']:.2f}x</td>
        <td style="padding:8px 12px;text-align:right;font-weight:700;color:{score_color};">{score}</td>
        <td style="padding:8px 12px;font-size:0.78em;color:#64748B;">{r['notes']}</td>
      </tr>"""

    table_html = f"""
    <table style="width:100%;border-collapse:collapse;font-size:0.83em;">
      <thead style="background:#0F172A;">
        <tr>
          <th style="{th}text-align:left;">Ticker</th>
          <th style="{th}text-align:left;">List</th>
          <th style="{th}text-align:right;">Price</th>
          <th style="{th}text-align:right;">RSI</th>
          <th style="{th}text-align:right;">vs SMA200</th>
          <th style="{th}text-align:right;">Vol Ratio</th>
          <th style="{th}text-align:right;">Score</th>
          <th style="{th}text-align:left;">Signals</th>
        </tr>
      </thead>
      <tbody>{rows_html}</tbody>
    </table>"""

    html_body = f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#020617;font-family:'Segoe UI',Arial,sans-serif;color:#F8FAFC;">
<div style="max-width:980px;margin:0 auto;padding:28px 16px;">
<div style="background:#1E293B;border:1px solid #334155;border-radius:12px;overflow:hidden;">

  <div style="padding:22px 28px;border-bottom:1px solid #334155;background:rgba(249,115,22,0.07);">
    <span style="font-size:1.3em;font-weight:800;">Stock<span style="color:#F97316;">Analyzer</span></span>
    <p style="margin:4px 0 0;font-size:0.85em;color:#94A3B8;">Accumulation Zone Report — {today_str}</p>
  </div>

  <div style="padding:18px 28px;border-bottom:1px solid #334155;">
    <p style="margin:0 0 4px;font-size:0.95em;">Hi {display_name},</p>
    <p style="margin:0;font-size:0.85em;color:#94A3B8;">
      <strong style="color:#F97316;">{count} ticker{'s' if count != 1 else ''}</strong>
      in the accumulation zone — near SMA200 with oversold RSI.
      These are <em>pre-signals</em>: no confirmation yet, enter with caution.
    </p>
  </div>

  <div style="padding:20px 16px 8px;">
    <p style="padding:0 0 10px;font-size:0.78em;font-weight:700;color:#64748B;text-transform:uppercase;letter-spacing:.08em;">
      Accumulation Signals ({count})
    </p>
    <div style="overflow-x:auto;">{table_html}</div>
  </div>

  <div style="padding:16px 28px;margin-top:8px;border-top:1px solid #334155;background:#0F172A;">
    <p style="margin:0;font-size:0.75em;color:#475569;">
      Pre-signal · No confirmation · Expect false positives ·
      Generated by StockAnalyzer · Not financial advice
    </p>
  </div>

</div>
</div>
</body>
</html>"""

    send_mail(
        subject=f'[StockAnalyzer] {count} Accumulation Signal{"s" if count != 1 else ""} — {today_str}',
        message=f'StockAnalyzer accumulation report {today_str}: {count} signal(s) in the zone.',
        from_email=None,
        recipient_list=[user.email],
        html_message=html_body,
        fail_silently=False,
    )


def _signal_color(signal):
    return {'BUY': '#22C55E', 'WATCH': '#F59E0B', 'NO_BUY': '#EF4444'}.get(signal, '#94A3B8')


def _signal_bg(signal):
    return {'BUY': 'rgba(34,197,94,0.15)', 'WATCH': 'rgba(245,158,11,0.15)',
            'NO_BUY': 'rgba(239,68,68,0.15)'}.get(signal, 'rgba(148,163,184,0.15)')


def _fmt(value, prefix='$', decimals=2):
    if value is None:
        return '—'
    try:
        return f"{prefix}{float(value):.{decimals}f}"
    except (TypeError, ValueError):
        return '—'


def _w52(ticker):
    one_year_ago = date.today() - timedelta(days=365)
    agg = ticker.prices.filter(date__gte=one_year_ago).aggregate(h=Max('high'), l=Min('low'))
    return _fmt(agg['h']), _fmt(agg['l'])


def _build_analysis_table(analysis_rows):
    th = "padding:9px 12px;color:#64748B;font-weight:600;font-size:0.78em;text-transform:uppercase;letter-spacing:.05em;white-space:nowrap;"
    header = f"""
    <thead style="background:#0F172A;">
      <tr>
        <th style="{th}text-align:left;">Ticker</th>
        <th style="{th}text-align:left;">Signal</th>
        <th style="{th}text-align:right;">Score</th>
        <th style="{th}text-align:right;">Entry</th>
        <th style="{th}text-align:right;">Stop</th>
        <th style="{th}text-align:right;">Target</th>
        <th style="{th}text-align:right;">R:R</th>
        <th style="{th}text-align:left;">Strategies</th>
        <th style="{th}text-align:right;">52W High</th>
        <th style="{th}text-align:right;">52W Low</th>
      </tr>
    </thead>"""

    rows = ''
    for row in analysis_rows:
        ticker   = row['ticker']
        analysis = row['analysis']
        if not analysis:
            continue

        color      = _signal_color(analysis.signal)
        bg         = _signal_bg(analysis.signal)
        strategies = ', '.join(analysis.strategies_triggered) if analysis.strategies_triggered else '—'
        w52h, w52l = _w52(ticker)
        entry_str  = _fmt(analysis.entry_price)
        stop_str   = _fmt(analysis.stop_loss)
        target_str = _fmt(analysis.take_profit)
        rr_str     = _fmt(analysis.risk_reward_ratio, prefix='', decimals=1) if analysis.risk_reward_ratio else '—'
        score_str  = f"{analysis.confidence_score}%"

        rows += f"""
      <tr style="border-bottom:1px solid #1E293B;">
        <td style="padding:9px 12px;font-weight:700;color:{color};">{ticker.symbol}</td>
        <td style="padding:9px 12px;">
          <span style="padding:2px 8px;border-radius:9999px;font-size:0.78em;font-weight:700;background:{bg};color:{color};">{analysis.signal}</span>
        </td>
        <td style="padding:9px 12px;text-align:right;font-weight:600;color:#F8FAFC;">{score_str}</td>
        <td style="padding:9px 12px;text-align:right;color:#F8FAFC;">{entry_str}</td>
        <td style="padding:9px 12px;text-align:right;color:#EF4444;">{stop_str}</td>
        <td style="padding:9px 12px;text-align:right;color:#22C55E;">{target_str}</td>
        <td style="padding:9px 12px;text-align:right;color:#F8FAFC;">{rr_str}</td>
        <td style="padding:9px 12px;color:#94A3B8;font-size:0.8em;">{strategies}</td>
        <td style="padding:9px 12px;text-align:right;color:#22C55E;font-size:0.85em;">{w52h}</td>
        <td style="padding:9px 12px;text-align:right;color:#EF4444;font-size:0.85em;">{w52l}</td>
      </tr>"""

    if not rows:
        rows = '<tr><td colspan="10" style="padding:16px;color:#94A3B8;text-align:center;">No data</td></tr>'

    return f'<table style="width:100%;border-collapse:collapse;font-size:0.85em;">{header}<tbody>{rows}</tbody></table>'


def _build_trade_table(trade_list):
    th = "padding:9px 12px;color:#64748B;font-weight:600;font-size:0.78em;text-transform:uppercase;letter-spacing:.05em;white-space:nowrap;"
    header = f"""
    <thead style="background:#0F172A;">
      <tr>
        <th style="{th}text-align:left;">Ticker</th>
        <th style="{th}text-align:left;">Strategy</th>
        <th style="{th}text-align:right;">Entry</th>
        <th style="{th}text-align:right;">Stop</th>
        <th style="{th}text-align:right;">Target</th>
        <th style="{th}text-align:right;">Shares</th>
        <th style="{th}text-align:right;">Risk $</th>
        <th style="{th}text-align:right;">Reward $</th>
        <th style="{th}text-align:right;">R:R</th>
        <th style="{th}text-align:center;">Action</th>
      </tr>
    </thead>"""

    rows = ''
    for trade in trade_list:
        action        = trade.action_label
        action_color  = '#22C55E' if action == 'BUY' else '#F59E0B' if action == 'WAIT' else '#EF4444'
        rr_color      = '#22C55E' if trade.rr_ratio >= 2.0 else '#F59E0B' if trade.rr_ratio >= 1.5 else '#EF4444'
        entry_str     = _fmt(trade.entry_price)
        stop_str      = _fmt(trade.stop_loss)
        target_str    = _fmt(trade.target_price) if trade.target_price else '—'
        risk_str      = _fmt(trade.risk_amount, decimals=0)
        reward_str    = _fmt(trade.reward_amount, decimals=0) if trade.reward_amount else '—'
        rr_str        = f"{trade.rr_ratio:.1f}"
        strategy_name = trade.get_strategy_type_display()

        rows += f"""
      <tr style="border-bottom:1px solid #1E293B;">
        <td style="padding:9px 12px;font-weight:700;color:#F8FAFC;">{trade.ticker.symbol}</td>
        <td style="padding:9px 12px;color:#94A3B8;font-size:0.85em;">{strategy_name}</td>
        <td style="padding:9px 12px;text-align:right;color:#F8FAFC;">{entry_str}</td>
        <td style="padding:9px 12px;text-align:right;color:#EF4444;">{stop_str}</td>
        <td style="padding:9px 12px;text-align:right;color:#22C55E;">{target_str}</td>
        <td style="padding:9px 12px;text-align:right;color:#F8FAFC;">{trade.position_size}</td>
        <td style="padding:9px 12px;text-align:right;color:#EF4444;">{risk_str}</td>
        <td style="padding:9px 12px;text-align:right;color:#22C55E;">{reward_str}</td>
        <td style="padding:9px 12px;text-align:right;font-weight:700;color:{rr_color};">{rr_str}</td>
        <td style="padding:9px 12px;text-align:center;">
          <span style="padding:2px 8px;border-radius:9999px;font-size:0.78em;font-weight:700;
            color:{action_color};background:{action_color}22;">{action}</span>
        </td>
      </tr>"""

        if trade.status == 'invalid' and trade.rejection_reason:
            rows += f"""
      <tr style="background:rgba(239,68,68,0.04);">
        <td colspan="10" style="padding:4px 12px 8px 24px;font-size:0.78em;color:#EF444499;font-style:italic;">
          ↳ {trade.rejection_reason}
        </td>
      </tr>"""

    if not rows:
        rows = '<tr><td colspan="10" style="padding:16px;color:#94A3B8;text-align:center;">No trade plans — run Analyze All first</td></tr>'

    return f'<table style="width:100%;border-collapse:collapse;font-size:0.85em;">{header}<tbody>{rows}</tbody></table>'


def _build_accumulation_table(acc_rows: list) -> str:
    th  = "padding:9px 12px;color:#64748B;font-weight:600;font-size:0.78em;text-transform:uppercase;letter-spacing:.05em;white-space:nowrap;"
    fmt = lambda v: f'${v:.2f}' if v is not None else '—'

    header = f"""
    <thead style="background:#0F172A;">
      <tr>
        <th style="{th}text-align:left;">Ticker</th>
        <th style="{th}text-align:left;">List</th>
        <th style="{th}text-align:left;">Fase</th>
        <th style="{th}text-align:right;">Price</th>
        <th style="{th}text-align:right;">RSI</th>
        <th style="{th}text-align:right;">Resist</th>
        <th style="{th}text-align:right;">Entry</th>
        <th style="{th}text-align:right;">Stop</th>
        <th style="{th}text-align:right;">Target</th>
        <th style="{th}text-align:right;">Score</th>
        <th style="{th}text-align:left;">Signals</th>
      </tr>
    </thead>"""

    rows = ''
    for r in acc_rows:
        is_ready    = r.get('signal_type') == 'READY_TO_BUY'
        ticker_color = '#22C55E' if is_ready else '#F97316'
        rsi          = r['rsi']
        rsi_color    = '#EF4444' if rsi <= 30 else '#F97316' if rsi <= 35 else '#F59E0B' if rsi <= 40 else '#22C55E'
        score        = r['score']
        score_color  = '#22C55E' if score >= 70 else '#F97316' if score >= 50 else '#F59E0B'
        row_bg       = 'background:rgba(34,197,94,0.04);' if is_ready else ''

        fase_html = (
            '<span style="padding:2px 7px;border-radius:9999px;font-size:0.72em;font-weight:800;'
            'background:rgba(34,197,94,0.15);color:#22C55E;">✓ LISTO</span>'
            if is_ready else
            '<span style="padding:2px 7px;border-radius:9999px;font-size:0.72em;font-weight:700;'
            'background:rgba(249,115,22,0.12);color:#F97316;">ESPERAR</span>'
        )

        rows += f"""
      <tr style="border-bottom:1px solid #1E293B;{row_bg}">
        <td style="padding:9px 12px;font-weight:700;color:{ticker_color};">{r['symbol']}</td>
        <td style="padding:9px 12px;font-size:0.8em;color:#475569;">{r['list_name']}</td>
        <td style="padding:9px 12px;">{fase_html}</td>
        <td style="padding:9px 12px;text-align:right;font-family:monospace;font-weight:600;color:#F8FAFC;">{fmt(r['price'])}</td>
        <td style="padding:9px 12px;text-align:right;font-family:monospace;font-weight:600;color:{rsi_color};">{rsi:.1f}</td>
        <td style="padding:9px 12px;text-align:right;font-family:monospace;color:#94A3B8;">{fmt(r.get('resistance'))}</td>
        <td style="padding:9px 12px;text-align:right;font-family:monospace;font-weight:700;color:{'#22C55E' if is_ready else '#475569'};">{fmt(r.get('entry'))}</td>
        <td style="padding:9px 12px;text-align:right;font-family:monospace;color:#EF4444;">{fmt(r.get('stop'))}</td>
        <td style="padding:9px 12px;text-align:right;font-family:monospace;color:#22C55E;">{fmt(r.get('target'))}</td>
        <td style="padding:9px 12px;text-align:right;font-weight:700;color:{score_color};">{score}</td>
        <td style="padding:9px 12px;font-size:0.78em;color:#64748B;">{r['notes']}</td>
      </tr>"""

    if not rows:
        rows = '<tr><td colspan="11" style="padding:16px;color:#94A3B8;text-align:center;">No accumulation signals</td></tr>'

    return f'<table style="width:100%;border-collapse:collapse;font-size:0.85em;">{header}<tbody>{rows}</tbody></table>'


def send_analysis_report_email(user, analysis_rows, trade_plans, accumulation_rows=None):
    if not user.email:
        return

    today_str    = date.today().strftime('%B %d, %Y')
    display_name = user.get_full_name() or user.username
    trade_list   = list(trade_plans)

    buy_rows       = [r for r in analysis_rows if r['analysis'] and r['analysis'].signal == 'BUY']
    valid_trades   = [t for t in trade_list if t.status == 'pending']
    n_buy          = len(buy_rows)
    n_valid_trades = len(valid_trades)
    n_accum        = len(accumulation_rows) if accumulation_rows else 0

    analysis_table = _build_analysis_table(buy_rows)
    trade_table    = _build_trade_table(valid_trades)

    section_label = "padding:0 0 10px 0;font-size:0.8em;font-weight:700;color:#64748B;text-transform:uppercase;letter-spacing:.08em;"

    # Accumulation section — only rendered when there are signals
    accum_section = ''
    if accumulation_rows:
        accum_table = _build_accumulation_table(accumulation_rows)
        accum_section = f"""
  <div style="padding:20px 16px 8px;border-top:1px solid #334155;">
    <div style="display:flex;align-items:center;gap:8px;padding-bottom:10px;">
      <span style="font-size:0.8em;font-weight:700;color:#64748B;text-transform:uppercase;letter-spacing:.08em;">
        Accumulation Zone ({n_accum})
      </span>
      <span style="padding:2px 8px;border-radius:9999px;font-size:0.72em;font-weight:700;
                   background:rgba(249,115,22,0.15);color:#F97316;border:1px solid rgba(249,115,22,0.3);">
        PRE-SIGNAL
      </span>
    </div>
    <p style="margin:0 0 10px;font-size:0.78em;color:#475569;">
      Near SMA200 with oversold RSI — before the move, no confirmation yet.
    </p>
    <div style="overflow-x:auto;">{accum_table}</div>
  </div>"""

    accum_summary = f' — <strong style="color:#F97316;">{n_accum} accumulation</strong>' if n_accum else ''

    html_body = f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#020617;font-family:'Segoe UI',Arial,sans-serif;color:#F8FAFC;">
<div style="max-width:980px;margin:0 auto;padding:28px 16px;">
<div style="background:#1E293B;border:1px solid #334155;border-radius:12px;overflow:hidden;">

  <div style="padding:22px 28px;border-bottom:1px solid #334155;background:rgba(34,197,94,0.07);">
    <span style="font-size:1.3em;font-weight:800;">Stock<span style="color:#22C55E;">Analyzer</span></span>
    <p style="margin:4px 0 0;font-size:0.85em;color:#94A3B8;">Analysis Report — {today_str}</p>
  </div>

  <div style="padding:18px 28px;border-bottom:1px solid #334155;">
    <p style="margin:0 0 4px;font-size:0.95em;">Hi {display_name},</p>
    <p style="margin:0;font-size:0.85em;color:#94A3B8;">
      <strong style="color:#22C55E;">{n_buy} BUY</strong> signal(s) —
      <strong style="color:#22C55E;">{n_valid_trades} valid</strong> trade plan(s){accum_summary}.
    </p>
  </div>

  <div style="padding:20px 16px 8px;">
    <p style="{section_label}">BUY Signals ({n_buy})</p>
    <div style="overflow-x:auto;">{analysis_table}</div>
  </div>

  <div style="padding:20px 16px 8px;border-top:1px solid #334155;">
    <p style="{section_label}">Valid Trade Plans ({n_valid_trades})</p>
    <div style="overflow-x:auto;">{trade_table}</div>
  </div>

{accum_section}

  <div style="padding:16px 28px;margin-top:8px;border-top:1px solid #334155;background:#0F172A;">
    <p style="margin:0;font-size:0.75em;color:#475569;">
      Generated by StockAnalyzer · Not financial advice · Toggle this email in your Profile settings.
    </p>
  </div>

</div>
</div>
</body>
</html>"""

    send_mail(
        subject=f'[StockAnalyzer] {n_buy} BUY · {n_valid_trades} Trade Plan(s){f" · {n_accum} Accum" if n_accum else ""} · {today_str}',
        message=f'StockAnalyzer report {today_str}: {n_buy} BUY signals, {n_valid_trades} valid trades, {n_accum} accumulation.',
        from_email=None,
        recipient_list=[user.email],
        html_message=html_body,
        fail_silently=False,
    )
