# Generated by Django 4.2.30 on 2026-04-25 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0002_tickeranalysis_sma9_data_stocklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickeranalysis',
            name='market_structure',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TradingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_size', models.FloatField(default=10000.0)),
                ('risk_per_trade_pct', models.FloatField(default=1.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_type', models.CharField(choices=[('pullback', 'Pullback'), ('breakout', 'Breakout'), ('sma9_pullback', 'SMA9 Pullback'), ('multi', 'Multi-Strategy')], default='pullback', max_length=20)),
                ('entry_price', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('target_price', models.FloatField(default=0)),
                ('position_size', models.IntegerField(default=0)),
                ('risk_amount', models.FloatField(default=0)),
                ('reward_amount', models.FloatField(default=0)),
                ('rr_ratio', models.FloatField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed_win', 'Closed – Win'), ('closed_loss', 'Closed – Loss'), ('invalid', 'Invalid')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.tickeranalysis')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='stocks.ticker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'ticker', 'analysis')},
            },
        ),
    ]
