# Generated by Django 4.2.30 on 2026-04-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_tickeranalysis_market_structure_tradingprofile_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingprofile',
            name='send_analysis_email',
            field=models.BooleanField(default=True),
        ),
    ]
