# Generated by Django 4.2.30 on 2026-04-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_tradingprofile_send_analysis_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='resistance_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='score_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='spy_alignment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='support_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='validation_reasons',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trade',
            name='validation_status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('WATCHLIST', 'Watchlist'), ('INVALID', 'Invalid')], default='INVALID', max_length=20),
        ),
    ]
