# Generated by Django 4.2.30 on 2026-05-01 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_trade_performance_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccumulationSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('price', models.FloatField()),
                ('rsi', models.FloatField()),
                ('dist_from_sma200_pct', models.FloatField()),
                ('vol_ratio', models.FloatField()),
                ('score', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accumulation_signals', to='stocks.ticker')),
            ],
            options={
                'ordering': ['-date', '-score'],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
