# Generated by Django 4.2.30 on 2026-05-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_accumulation_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='accumulationsignal',
            name='entry_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accumulationsignal',
            name='resistance_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accumulationsignal',
            name='signal_type',
            field=models.CharField(choices=[('ACCUM', 'Accumulation'), ('READY_TO_BUY', 'Ready to Buy')], default='ACCUM', max_length=15),
        ),
        migrations.AddField(
            model_name='accumulationsignal',
            name='stop_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accumulationsignal',
            name='target_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
