# Generated by Django 4.2.30 on 2026-05-02 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0009_accumulation_ready_to_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('BUY_SIGNAL', 'BUY Signal'), ('READY_TO_BUY', 'Ready to Buy'), ('MANUAL', 'Manual')], default='BUY_SIGNAL', max_length=15)),
                ('entry_price', models.FloatField()),
                ('shares', models.IntegerField()),
                ('stop_loss', models.FloatField()),
                ('target_price', models.FloatField()),
                ('capital_used', models.FloatField()),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED_WIN', 'Closed — Win'), ('CLOSED_LOSS', 'Closed — Loss'), ('CLOSED_MANUAL', 'Closed — Manual')], default='OPEN', max_length=15)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('pnl_dollars', models.FloatField(blank=True, null=True)),
                ('pnl_percent', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='stocks.paperportfolio')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_trades', to='stocks.ticker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='stocks.paperportfolio')),
            ],
        ),
    ]
