# Generated by Django 4.2.30 on 2026-05-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_paper_trading'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['portfolio', 'status'], name='stocks_pape_portfol_abed04_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'paper_status'], name='stocks_trad_user_id_ed17e5_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user', 'validation_status'], name='stocks_trad_user_id_0100d1_idx'),
        ),
    ]
